#
#Sun Sep 08 20:03:31 CEST 2019
extensionProposed=true
author=viatsko
archiveDirectory=algorithms/codeforces/archive/unsorted
failOnIntegerOverflowForNewTasks=true
libraryVersion=2
excludePackages=java.,javax.,com.sun.
testDirectory=lib/test
smartTesting=false
inputClass=java.util.Scanner
defaultDirectory=algorithms/codeforces/main/sources
outputClass=java.io.PrintWriter
enableUnitTests=false
outputDirectory=algorithms/codeforces/output
