1. Для начала нужно установить nodejs для Мака.

1.1. Чтобы была возможность поставить nodejs, нужен homebrew.

1.2. Идем на сайт http://brew.sh/

1.3. Копируем ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" в терминал
     и ждем пока установится, Homebrew может потребовать установленной XCode, можно поставить через AppStore.

1.4. Как только homebrew поставился, вводим в терминале brew install nodejs

1.5. ЕСЛИ СТАВИМ НА UBUNTU LINUX, НАПРИМЕР, ТО КОМАНДА ДЛЯ УСТАНОВКИ NODEJS - aptitude install nodejs и
 aptitude install nodejs-legacy

2. Идем в папку с ботом в терминале, например cd ~/Downloads/twitchbot

2.1. Вводим npm install в папке с ботом, пройдет достаточно много времени, ошибки можно проигнорить на Mac и Linux,
на Windows прийдется ставить Python и т. п.

3. Идем в папку configs/ бота, в файликах:

_auth.js - логины и пароли
_global.js - глобальные настройки всякие, например интервал спама 30000 мс = 30 секунд
_spamMessages.js - сообщения для спама

bot1, bot2, bot3 - конфиги ботов, на самом деле на одном компе может быть тупо bot1 или bot2 или bot3, важно чтобы
в _global у них был один канал, с него они будут управляться.

4. Как только настроили всех ботов, через терминал опять же у нас три варианта запуска:

./bin/run-all.sh - запустить ВСЕХ ботов - и мастера и 3 подчиненных в стандартном комплекте
./bin/run-master.sh - запустить ТОЛЬКО мастера (он юзает конфиг configs/master)
./bin/run-slaves.sh - запустить ТОЛЬКО подчиненных ботов (они юзают конфиги configs/botX, если называть их по-другому,
то они будут работать, но не будут понимать команды мастер-бота, например если назвать botHren, то он будет понимать команду
!assign botHren trumpsc, но не будет получать канал от мастера по команде !top20)

Если нужно запустить какого-то отдельного бота, то команда например:

node slave-bot configs/bot10.js

5. Как этим делом управлять:

По умолчанию в конфиге, и если запускать ./bin/run-all.sh, боты сядут в канале dwrsc2, на него можно зайти человеком
например через http://www.twitch.tv/dwrsc2/chat, туда боты и спамят то, что они спамят в другие каналы, и принимают команды.

Список команд прост, для клиентов это:

!assign имя_бота стрим

!assign bot1 trumpsc

Для мастер бота это команды:

!ignore стрим
!unignore стрим
!top20

Собственно, нужно ввести команду !top20 на команде с ботами и мастер им раздаст указания, пример:

dwrsc2: !top20
dwrsc2: 1. nahj - 1149 [assigned to bot1]
dwrsc2: !assign bot1 nahj
dwrsc2: 2. seriousgaming - 609 [assigned to bot2]
dwrsc2: !assign bot2 seriousgaming
dwrsc2: 3. xaryulol - 377 [assigned to bot3]
dwrsc2: !assign bot3 xaryulol
Kelopalapa: Me assigned to nahj
Dodilakoiola: Me assigned to seriousgaming
Tiratitarr: Me assigned to xaryulol

Как только бот написал "Me assigned", он уходит на выбранный канал и спамит, проверить можно зайдя на этот канал:

http://www.twitch.tv/nahj/chat

6. Проблемы и возможные решения

6.1. Падает на папке logs/

Нужно просто создать ее в папке с ботом (по идее, не потребуется)
