/**
 * Actions
 */

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_UPDATE_ITEM_QUANTITY = 'CART_UPDATE_ITEM_QUANTITY';
export const CART_UPDATE_ITEM_PROPERTIES = 'CART_UPDATE_ITEM_PROPERTIES';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';
export const CART_SAVE = 'CART_SAVE';
export const CART_SAVE_SUCCESS = 'CART_SAVE_SUCCESS';
export const CART_SAVE_ERROR = 'CART_SAVE_ERROR';
export const CART_RESTORE = 'CART_RESTORE';
export const CART_RESTORE_SUCCESS = 'CART_RESTORE_SUCCESS';
export const CART_RESTORE_ERROR = 'CART_RESTORE_ERROR';
